---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mb-test
  labels:
    serviceType: mb-test
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: /metrics
        prometheus.io/port: '9080'
      name: mb-test
      labels:
        serviceType: mb-test
    spec:
      containers:
        - name: mb-test
          image: kuperiu/mb-test
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 9080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 5
            
---
apiVersion: v1
kind: Service
metadata:
  name: mb-test-svc
  namespace: default
spec:
  selector:
    serviceType: mb-test
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9080
      name: http
